name: Action

on:
  push:
    branches:
      - main  # default branch
jobs:
  do_action:
    runs-on: daoTrip
    steps:
      - name: run notifyAction
        uses: daoAction/wait/@main
        with:
          milliseconds: 39999
